# Generated by Django 3.0.8 on 2020-08-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demopostgre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
