# Generated by Django 3.0.8 on 2020-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('stop_time', models.CharField(max_length=100)),
                ('total_time', models.CharField(max_length=100)),
            ],
        ),
    ]
