# Generated by Django 3.0.8 on 2020-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='taskdata',
            table='app2_taskdata',
        ),
    ]
