# Generated by Django 3.0.8 on 2020-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200919_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterModelTable(
            name='taskdata',
            table='TaskData',
        ),
    ]
