# Generated by Django 3.0.8 on 2020-09-19 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20200919_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='Date',
            field=models.CharField(default=datetime.datetime(2020, 9, 19, 17, 34, 24, 586062, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
